apiVersion: v1
kind: Service
metadata:
  name: hello-world-cluster-ip-2
spec:
  type: ClusterIP
  selector:
    greeting: hello
    version: two
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
