apiVersion: v1
kind: Service
metadata:
  name: hello-world-cluster-ip-1
spec:
  type: ClusterIP
  selector:
    greeting: hello
    version: one
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 50000
